# This is a basic workflow to help you get started with Actions

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: install dependencies
        run: npm ci
      - name: Build
        run: CI=false npm run build
        env:
          REACT_APP_GA: ${{ secrets.REACT_APP_GA }}
          REACT_APP_DEPLOY_QUERY_ID: ${{ secrets.REACT_APP_DEPLOY_QUERY_ID }} # sha256("jetton.live").toDecimal() sliced to fit 53 bit (BN assertion, though query id allows 64) = 1083895200524364
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
